### ISSUE TITLE
add row set child col count

### ISSUE THREAD

**Issue by imagine10255** [acrool/acrool-react-grid#10]
ref: https://getbootstrap.com/docs/5.3/examples/album/

```css
@media (min-width: 768px) {
    .row-cols-md-3>* {
        flex: 0 0 auto;
        width: 33.33333333%;
    }
}
```

![Image](https://github.com/user-attachments/assets/7ad71752-de81-44ab-aaef-fba27d6480bd)
