### ISSUE TITLE
Added tool CSS class - white-space: pre-line

### ISSUE THREAD

**Issue by imagine10255** [acrool/acrool-react-grid#8]
```css
.text-pre{white-space: pre !important;}
.text-pre-line{white-space: pre-line !important;}
```

```ts
[
            {
                bet: '000\n' +
                    '111\n' +
                    '⦙\n' +
                    '888\n' +
                    '999',
                desc: 'Any set of identical numbers, i.e., all digits are the same, wins.'
            },
            {
                bet: '000',
                desc: 'The last digits of the three lottery results are 0 0 0'
            },
            {
                bet: '111',
                desc: 'The last digits of the three lottery results are 1 1 1'
            },
        ]
```
example: 

![CleanShot 2024-10-29 at 14 22 25](https://github.com/user-attachments/assets/39f9c90c-42f4-40b5-992b-4247e69051f9)
